Fix timeouts in some unary calls, increment go-libp2p to 0.24 (#23)
### Changes
* switches to go-libp2p v0.24 (minor changes)
* sets specific package versions for libp2p 0.24
* fixes a bug that caused p2pd to skip some unary handlers
* added small timeouts after adding new handlers to de-flappify tests (based on massive parallel test runs)
* in tests, added a small timeout after adding handlers, before calling them for the first time (otherwise there are rare random failures)
* TestBalancedStreams would fail because not all handlers got added before you started calling them
   - the test failed because it assumed a fixed number of active handlers but got less because some were still getting added
   - fixed with timeout, now considering a safer fix


### Remaining issues (based on [42 runs](https://github.com/learning-at-home/go-libp2p-daemon/actions/runs/3646465087/jobs/6157578319)):

<details>
<summary> race detected in TestBalancedCall </summary>

```
  === RUN   TestBalancedCall
  2022-12-08T08:16:37.217Z	ERROR	p2pd	go-libp2p-daemon/daemon.go:179	error accepting connection	{"error": "accept unix /tmp/p2pd3945415430/daemon.sock: use of closed network connection"}
  2022-12-08T08:16:37.218Z	ERROR	p2pd	go-libp2p-daemon/daemon.go:179	error accepting connection	{"error": "accept unix /tmp/p2pd1614730452/daemon.sock: use of closed network connection"}
      unary_handler_test.go:325: numbered handler x = 1
      unary_handler_test.go:325: numbered handler x = -1
      unary_handler_test.go:325: numbered handler x = 1
      unary_handler_test.go:325: numbered handler x = -1
      unary_handler_test.go:325: numbered handler x = 1
      unary_handler_test.go:325: numbered handler x = -1
      unary_handler_test.go:325: numbered handler x = 1
      unary_handler_test.go:325: numbered handler x = -1
      unary_handler_test.go:325: numbered handler x = 1
      unary_handler_test.go:325: numbered handler x = -1
  ==================
  WARNING: DATA RACE
  Read at 0x00c000f31800 by goroutine 599:
    reflect.Value.Uint()
        /opt/hostedtoolcache/go/1.18.8/x64/src/reflect/value.go:2506 +0xb0d
    reflect.deepValueEqual()
        /opt/hostedtoolcache/go/1.18.8/x64/src/reflect/deepequal.go:162 +0xa60
    reflect.deepValueEqual()
        /opt/hostedtoolcache/go/1.18.8/x64/src/reflect/deepequal.go:130 +0x209b
    reflect.deepValueEqual()
        /opt/hostedtoolcache/go/1.18.8/x64/src/reflect/deepequal.go:130 +0x209b
    reflect.deepValueEqual()
        /opt/hostedtoolcache/go/1.18.8/x64/src/reflect/deepequal.go:130 +0x209b
    reflect.deepValueEqual()
        /opt/hostedtoolcache/go/1.18.8/x64/src/reflect/deepequal.go:127 +0xf79
    reflect.deepValueEqual()
        /opt/hostedtoolcache/go/1.18.8/x64/src/reflect/deepequal.go:130 +0x209b
    reflect.deepValueEqual()
        /opt/hostedtoolcache/go/1.18.8/x64/src/reflect/deepequal.go:130 +0x209b
    reflect.deepValueEqual()
        /opt/hostedtoolcache/go/1.18.8/x64/src/reflect/deepequal.go:127 +0xf79
    reflect.deepValueEqual()
        /opt/hostedtoolcache/go/1.18.8/x64/src/reflect/deepequal.go:130 +0x209b
    reflect.deepValueEqual()
        /opt/hostedtoolcache/go/1.18.8/x64/src/reflect/deepequal.go:127 +0xf79
    reflect.deepValueEqual()
        /opt/hostedtoolcache/go/1.18.8/x64/src/reflect/deepequal.go:122 +0x1ad2
    reflect.deepValueEqual()
        /opt/hostedtoolcache/go/1.18.8/x64/src/reflect/deepequal.go:130 +0x209b
    reflect.deepValueEqual()
        /opt/hostedtoolcache/go/1.18.8/x64/src/reflect/deepequal.go:127 +0xf79
    reflect.deepValueEqual()
        /opt/hostedtoolcache/go/1.18.8/x64/src/reflect/deepequal.go:122 +0x1ad2
    reflect.deepValueEqual()
        /opt/hostedtoolcache/go/1.18.8/x64/src/reflect/deepequal.go:130 +0x209b
    reflect.deepValueEqual()
        /opt/hostedtoolcache/go/1.18.8/x64/src/reflect/deepequal.go:127 +0xf79
    reflect.DeepEqual()
        /opt/hostedtoolcache/go/1.18.8/x64/src/reflect/deepequal.go:237 +0x3f9
    github.com/libp2p/go-libp2p-daemon/internal/utils.(*RoundRobin).Remove()
        /home/runner/work/go-libp2p-daemon/go-libp2p-daemon/internal/utils/round_robin.go:25 +0x2e6
    github.com/libp2p/go-libp2p-daemon.(*Daemon).handlePersistentConn.func1()
        /home/runner/work/go-libp2p-daemon/go-libp2p-daemon/persistent_stream.go:27 +0x1ca
    runtime.deferreturn()
        /opt/hostedtoolcache/go/1.18.8/x64/src/runtime/panic.go:436 +0x32
    github.com/libp2p/go-libp2p-daemon.(*Daemon).handleConn()
        /home/runner/work/go-libp2p-daemon/go-libp2p-daemon/conn.go:160 +0x12f9
    github.com/libp2p/go-libp2p-daemon.(*Daemon).Serve.func1()
        /home/runner/work/go-libp2p-daemon/go-libp2p-daemon/daemon.go:184 +0x58
  
  Previous write at 0x00c000f31800 by goroutine 781:
    sync/atomic.CompareAndSwapInt64()
        /opt/hostedtoolcache/go/1.18.8/x64/src/runtime/race_amd64.s:314 +0xb
    sync/atomic.CompareAndSwapUint64()
        <autogenerated>:1 +0x24
    internal/poll.(*FD).readLock()
        /opt/hostedtoolcache/go/1.18.8/x64/src/internal/poll/fd_mutex.go:221 +0x78
    internal/poll.(*FD).Read()
        /opt/hostedtoolcache/go/1.18.8/x64/src/internal/poll/fd_unix.go:144 +0x89
    net.(*netFD).Read()
        /opt/hostedtoolcache/go/1.18.8/x64/src/net/fd_posix.go:55 +0x50
    net.(*conn).Read()
        /opt/hostedtoolcache/go/1.18.8/x64/src/net/net.go:183 +0xb0
    go.(*struct { *net.UnixConn; github.com/multiformats/go-multiaddr/net.maEndpoints }).Read()
        <autogenerated>:1 +0x70
    bufio.(*Reader).fill()
        /opt/hostedtoolcache/go/1.18.8/x64/src/bufio/bufio.go:106 +0x293
    bufio.(*Reader).ReadByte()
        /opt/hostedtoolcache/go/1.18.8/x64/src/bufio/bufio.go:264 +0x4a
    encoding/binary.ReadUvarint()
        /opt/hostedtoolcache/go/1.18.8/x64/src/encoding/binary/varint.go:115 +0x8b
    github.com/gogo/protobuf/io.(*varintReader).ReadMsg()
        /home/runner/go/pkg/mod/github.com/gogo/protobuf@v1.3.2/io/varint.go:110 +0x70
    github.com/libp2p/go-libp2p-daemon.(*Daemon).handlePersistentConn()
        /home/runner/work/go-libp2p-daemon/go-libp2p-daemon/persistent_stream.go:51 +0x57c
    github.com/libp2p/go-libp2p-daemon.(*Daemon).handleConn()
        /home/runner/work/go-libp2p-daemon/go-libp2p-daemon/conn.go:160 +0x12f9
    github.com/libp2p/go-libp2p-daemon.(*Daemon).Serve.func1()
        /home/runner/work/go-libp2p-daemon/go-libp2p-daemon/daemon.go:184 +0x58
  
  Goroutine 599 (running) created at:
    github.com/libp2p/go-libp2p-daemon.(*Daemon).Serve()
        /home/runner/work/go-libp2p-daemon/go-libp2p-daemon/daemon.go:184 +0x2a9
    github.com/libp2p/go-libp2p-daemon/test.createDaemon.func1()
        /home/runner/work/go-libp2p-daemon/go-libp2p-daemon/test/utils.go:50 +0x39
  
  Goroutine 781 (running) created at:
    github.com/libp2p/go-libp2p-daemon.(*Daemon).Serve()
        /home/runner/work/go-libp2p-daemon/go-libp2p-daemon/daemon.go:184 +0x2a9
    github.com/libp2p/go-libp2p-daemon/test.createDaemon.func1()
        /home/runner/work/go-libp2p-daemon/go-libp2p-daemon/test/utils.go:50 +0x39
  ==================
      testing.go:1312: race detected during execution of test
  --- FAIL: TestBalancedCall (11.61s)
  === CONT  
      testing.go:1312: race detected during execution of test
```

</details>

<details>
<summary> flappy TestPubsubMessages </summary>

```
   === RUN   TestPubsubMessages
  2022-12-08T08:51:15.394Z	ERROR	p2pclient	p2pclient/pubsub.go:88	reading pubsub message	{"error": "read tcp4 127.0.0.1:54492->127.0.0.1:54490: use of closed network connection"}
      pubsub_test.go:74: timed out waiting for message
  2022-12-08T08:51:25.467Z	ERROR	p2pclient	p2pclient/pubsub.go:88	reading pubsub message	{"error": "read tcp4 127.0.0.1:54503->127.0.0.1:54500: use of closed network connection"}
  --- FAIL: TestPubsubMessages (10.06s)
```

</details>


<details>
<summary> context deadline exceeded in TestConnect </summary>

```
 === RUN   TestConnect
      integration_test.go:52: context deadline exceeded
  --- FAIL: TestConnect (60.04s)
```

</details>

<details>
<summary> Internal debug message: {"error": "invalid UUID (got 0 bytes)"} </summary>

Full message reads as follows.

```
2022-12-08T07:04:01.1776230Z 2022-12-08T07:02:42.278Z	DEBUG	p2pclient	p2pclient/unary_handlers.go:52	received response with bad call id:	{"error": "invalid UUID (got 0 bytes)"}
```

P2PClient (in go) writes large amounts of these messages, sometimes thousands of them. The message itself is *empty*. I have no idea why - could be a timeout - or we are serializing as a message of wrong type.

</details>


Wontfix:
- found the cause for {"error": "read unix @->/tmp/p2pd203243569/daemon.sock: use of closed network connection"}
   - this happens when a client is subscribed to a topic but a server shuts down on. It happens normally during test teardown.
   - I believe that this warning is harmless, it was there before we switched to new libp2p 


Co-authored-by: Pavel Samygin <44449246+greenfatguy@users.noreply.github.com>
Co-authored-by: Alexander Borzunov <borzunov.alexander@gmail.com>